### PR TITLE
Update package.json

### PR DESCRIPTION
**Pull request by ssebro**
I know connect-busboy's a simple wrapper, but without some control of what you're wrapping, you're basically allowing unfettered busboy updates onto random servers. This will be a real problem if busboy ever has a breaking api change.

### CODE REVIEW

**Comment by mscdex** [comment]
Restricting it to `0.0.x` doesn't make sense. The current version is 0.2.9.

**Comment by mscdex** [comment]
Also, when would you expect the dependency to be updated? Only when `connect-busboy` bumps a 0.x version?

**Comment by ssebro** [comment]
You could either do something like ^0.x (should ensure backwards compatibility with some patch+feature upgrade potential) or something like 0.x.

**Comment by mscdex** [comment]
Closing this as `busboy` has now moved to 1.0.0 and the semver range has been updated accordingly.

**Pull request closed without merging**
